Merge/collection upgrade
OpenDataCubePipelines/eugl pull request #29
Opened 2019-01-23 00:18 UTC by ASVincent

merge of the collection upgrade branch onto the main trunk.

No conflicts to resolve by git.

2019-01-23 00:29 UTC, passangd approved these changes

2019-01-23 00:37 UTC, uchchwhash requested changes

2019-01-23 00:37 UTC, uchchwhash commented on eugl/contiguity.py
> +        # TODO needs platform to be passed too
Looks like an important TODO not yet resolved. @passangd might be able to help here.

2019-01-23 02:15 UTC, passangd submitted a review, later dismissed

2019-01-28 21:30 UTC, passangd approved these changes

2019-01-28 23:40 UTC, merged